version: "3"
services:
    database:
        container_name: memodatabase
        image: postgres
        restart: always
        ports:
        - 5432:5432
        environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=teste
        - POSTGRES_DB=memo
        env_file: 
        - .env.example
        networks:
        - app-connect
        volumes:
        - pgdata:/var/lib/postgresql/data
    redis:
        container_name: memoredis
        image: redis:latest
        restart: unless-stopped
        ports:
        - "6379:6379"
        networks:
        - app-connect
    memoapp:
        build: .
        command: npm run dev:server
        ports:
        - "3333:3333"
        depends_on:
        - database
        - redis
        volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
        networks:
        - app-connect
volumes:
    pgdata:
        driver: local

networks:
    app-connect:
        driver: bridge