version: "3"
services:
    database:
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        image: mariadb:10
        restart: always
        volumes:
            - mysqldata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: memo
            MYSQL_USER: docker
            MYSQL_PASSWORD: teste
            MYSQL_ROOT_PASSWORD: teste
        ports:
            - 3306:3306
        networks:
            - app-connect
    redis:
        container_name: memoredis
        image: redis:latest
        restart: unless-stopped
        ports:
        - "6379:6379"
        networks:
        - app-connect
    memoapp:
        build: .
        command: npm run dev:server
        ports:
        - "3333:3333"
        depends_on:
        - database
        - redis
        volumes:
        - ./:/usr/src/app
        - /usr/src/app/node_modules
        networks:
        - app-connect
volumes:
    mysqldata:
        driver: local

networks:
    app-connect:
        driver: bridge